### ISSUE TITLE
ZeroDivisionError: divided by 0

### ISSUE THREAD

**Issue by 8398a7** [8398a7/abilitysheet#819]
https://sentry.io/personal-qs/abilitysheet/issues/196673975/

```
ZeroDivisionError: divided by 0
  raven/cli.rb:30:in `/'
    1 / 0
  raven/cli.rb:30:in `test'
    1 / 0
  raven/integrations/tasks.rb:9:in `block (2 levels) in <top (required)>'
    Raven::CLI.test(args.dsn)
  rake/task.rb:248:in `block in execute'
    act.call(self, args)
  rake/task.rb:243:in `each'
    @actions.each do |act|
...
(18 additional frame(s) were not displayed)

ZeroDivisionError: divided by 0
```

**Comment by 8398a7** [comment]
ok
