### ISSUE TITLE
bundlerのバージョンによってpuma:restartの挙動が変わる

### ISSUE THREAD

**Issue by 8398a7** [8398a7/abilitysheet#982]
bundler v1.15.1だと素直にpumactlでrestartを送っている

```
00:00 puma:restart
      01 bundle exec pumactl -S /var/www/app/abilitysheet/shared/tmp/pids/puma.state -F /var/www/app/abilitysheet/shared/puma.rb restart
      01 Command restart sent success
    ✔ 01 deploy@iidx12 0.719s
```

bundler v1.14.6だとpuma:stop puma:startを内部的に送っている

```
00:00 puma:stop
      01 bundle exec pumactl -S /var/www/app/abilitysheet/shared/tmp/pids/puma.state -F /var/www/app/abilitysheet/shared/puma.rb stop
      01 Command stop sent success
      01
    ✔ 01 deploy@iidx12 0.717s
00:01 puma:start
      using conf file /var/www/app/abilitysheet/shared/puma.rb
      01 bundle exec puma -C /var/www/app/abilitysheet/shared/puma.rb --daemon
      01 [13803] Puma starting in cluster mode...
      01
      01 [13803] * Version 3.9.1 (ruby 2.4.1-p111), codename: Private Caller
      01
      01 [13803] * Min threads: 8, max threads: 32
      01
      01 [13803] * Environment: production
      01
      01 [13803] * Process workers: 3
      01
      01 [13803] * Preloading application
      01
      01 [13803] * Listening on unix:///var/www/app/abilitysheet/shared/tmp/sockets/puma.sock
      01 [13803] * Daemonizing...
    ✔ 01 deploy@iidx12 4.996s

```

まずここの条件分岐が謎。

ついでにrestartを送ると

```
/usr/local/rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem puma (>= 0.a) (Gem::GemNotFoundException)
        from /usr/local/rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems.rb:298:in `activate_bin_path'
        from /var/www/app/abilitysheet/shared/bundle/ruby/2.4.0/bin/puma:22:in `<main>'
```

という例外でrestartがしない。

```ruby
#!/usr/bin/env ruby
#
# This file was generated by RubyGems.
#
# The application 'puma' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

load Gem.activate_bin_path('puma', 'puma', version)
```

```ruby
  def self.activate_bin_path name, exec_name, requirement # :nodoc:
    spec = find_spec_for_exe name, exec_name, [requirement]
    Gem::LOADED_SPECS_MUTEX.synchronize { spec.activate }
    spec.bin_file exec_name
  end
```

```ruby
  def self.find_spec_for_exe name, exec_name, requirements
    dep = Gem::Dependency.new name, requirements

    loaded = Gem.loaded_specs[name]

    return loaded if loaded && dep.matches_spec?(loaded)

    specs = dep.matching_specs(true)

    raise Gem::GemNotFoundException,
          "can't find gem #{dep}" if specs.empty?

    specs = specs.find_all { |spec|
      spec.executables.include? exec_name
    } if exec_name

    unless spec = specs.first
      msg = "can't find gem #{name} (#{requirements}) with executable #{exec_name}"
      raise Gem::GemNotFoundException, msg
    end

    spec
  end
  private_class_method :find_spec_for_exe
```

capistrano-puma 3.1.0で起きているが、そういう条件分岐は無いような気がした。
https://github.com/seuros/capistrano-puma/blob/v3.1.0/lib/capistrano/tasks/puma.rake#L59
binに吐かれるpumaファイル自体も同様のものだった。

**Comment by 8398a7** [comment]
bundler 1.14.6にしても特に解消していなかった。
ttps://github.com/puma/puma/issues/1308
当たりが関係していそう

bundlerを読み込んでないのが問題っぽい？

**Comment by 8398a7** [comment]
pumaの問題っぽい。最新版なら修正されてるっぽいのでクローズ。
